spring.application.name=prenotazione-sale

# Server
server.port=8080

# Entra ID - validazione token JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/f7237773-4b37-4214-b0e6-9d3322541036/

# Microsoft Graph - client credentials
app.azure.tenant-id=f7237773-4b37-4214-b0e6-9d3322541036
app.azure.client-id=89b12e43-1d18-43d5-b4a1-cb140eca77f5
app.azure.client-secret=${AZURE_CLIENT_SECRET}

# CORS - permette chiamate dal frontend React
app.cors.allowed-origins=http://localhost:5173

# Ruolo admin
app.admin-role=RoomBooking.Admin